import ReduxProvider from "../reduxProvider/Provider";
import "./globals.css";

export const metadata = {
  title: "Contact Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <ReduxProvider>{children}</ReduxProvider>
        </div>
      </body>
    </html>
  );
}
